# Site settings
title: Aditya Bobde
email: you@example.com
description: Personal academic website
baseurl: ""
url: "https://adityabobde19.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Include files
include:
  - _pages

# Max content width
max_width: 800px

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  news:
    output: true
    permalink: /news/:path/

# Navigation
header_pages:
  - about.md
  - research.md

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache

# Third party libraries
third_party_libraries:
  download: false
